### ISSUE TITLE
About the name of the tank dataset?

### ISSUE THREAD

**Issue by EEWenbinWu** [yazan2241/Tank-Detection#2]
Hi, thx for your release, could you please tell me the name of the tank dataset?

**Comment by yazan2241** [comment]
I Used an Open Images dataset which i used a tool to download images and label them

you can find the data set from this link
https://storage.googleapis.com/openimages/web/visualizer/index.html?set=train&type=detection&c=%2Fm%2F07cmd

you can find the tool (OIDv4_ToolKit) details from this link :
https://github.com/theAIGuysCode/OIDv4_ToolKit

there are a lot of dataset which useful in this case such as :

Military Tanks Dataset (Images) from Kaggle
here is the link :
https://www.kaggle.com/datasets/antoreepjana/military-tanks-dataset-images

if you need any help , feel free to contact me.
Good luck

**Comment by EEWenbinWu** [comment]
Thx a lot, I have downloaded the 1000 images from OID. Will you release the data you labeled?

**Comment by yazan2241** [comment]
I am really sorry , i remember that i created a project on roboflow but i could not find it.

**Comment by EEWenbinWu** [comment]
thx you all the same.

**Comment by yazan2241** [comment]
I hope this was helpful, if it is not let me know what are you looking for , i might be able to help you.
